### ISSUE TITLE
vscode에서 eslint가 적용되지 않는 현상

### ISSUE THREAD

**Issue by snowcuphea** [team-grass-farm/uncloudy-grapher#50]
개인 vscode에서 eslint가 적용되지 않습니다.
eslint를 설치하였으나, 적용되지 않습니다.
![image](https://user-images.githubusercontent.com/23146233/180225867-9fe1d32a-7a61-4e0c-b9cb-6aae2bef9091.png)

**Comment by 100kimch** [comment]
스크린샷 한장만으로는 알수가 없으니... 우선 Eslint 적용하지 않고 개발 진행하시고 회의때 확인해볼게요
